kind: pipeline
type: ssh
name: build-pi

server:
  host: pi.lan
  user: pi
  password:
    from_secret: pi_password

steps:
 - name: build
   commands:
   - make
 - name: package
   commands:
     - make package
   when:
     branch: master
---
kind: pipeline
type: ssh
name: build-arch-linux

server:
  host: server.lan
  user:
    from_secret: server_user
  password:
    from_secret: server_password

steps:
  - name: build
    commands:
      - make
  - name: package
    commands:
      - make package
    when:
      branch: master
