kind: pipeline
type: ssh
name: build-pi

server:
  host: pi.lan
  user: pi
  password:
    from_secret: pi_password

steps:
  - name: build
    commands:
      - make
  - name: package
    commands:
      - make package
    when:
      event: tag

---

kind: pipeline
type: ssh
name: build-arch-linux

server:
  host: server.lan
  user:
    from_secret: server_user
  password:
    from_secret: server_password

steps:
  - name: build
    commands:
      - make
  - name: package & publish
    commands:
      - make package
      - export RELEASE=$(curl -s "https://api.github.com/repos/lamarios/unifi-throughput-ncurses/releases/tags/${DRONE_TAG}" |  jq .id)
      - echo $RELEASE
      - export FILE=$(ls unifi-throughput-*.tar.gz)
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event: tag
