kind: pipeline
type: ssh
name: build-pi

server:
  host: pi.lan
  user: pi
  password:
    from_secret: pi_password

steps:
  - name: build
    commands:
      - make
  - name: package
    commands:
      - make package
    when:
      event: tag

---

kind: pipeline
type: ssh
name: build-arch-linux

server:
  host: server.lan
  user:
    from_secret: server_user
  password:
    from_secret: server_password

steps:
  - name: build
    commands:
      - make
  - name: package & publish
    commands:
      - make package
      - export RELEASE=$(curl -s "https://api.github.com/repos/lamarios/unifi-throughput-ncurses/releases/tags/${DRONE_TAG}" |  jq .id)
      - export FILE="$(ls unifi-throughput-*.tar.gz)"
      - export FILE_PATH="$(pwd)/$FILE"
      - echo "Release $RELEASE, File $FILE - $FILE_PATH"
      - curl --location --request POST "https://uploads.github.com/repos/lamarios/unifi-throughput-ncurses/releases/$RELEASE/assets?access_token=$GITHUB_TOKEN&name=$FILE" --data-binary "@$FILE_PATH"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event: tag
