kind: pipeline
type: ssh
name: build-pi

server:
  host: pi.lan
  user: pi
  password:
    from_secret: pi_password

steps:
  - name: build
    commands:
      - make
  - name: package
    commands:
      - make package
    when:
      event: tag

---

kind: pipeline
type: ssh
name: build-arch-linux

server:
  host: server.lan
  user:
    from_secret: server_user
  password:
    from_secret: server_password

steps:
  - name: build
    commands:
      - make
  - name: update AUR
    commands:
      - git clone ssh://aur@aur.archlinux.org/unifi-throughput-ncurses.git aur
      - cd aur
      - makepkg -s
      - makepkg --printsrcinfo > .SRCINFO
      - git add PKGBUILD .SRCINFO
      - git commit -m "update version"
      - git push
    when:
      event: tag
  - name: package
    commands:
      - make package
      - ./upload_release.sh
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event: tag
