kind: pipeline
type: ssh
name: build-pi

server:
  host: pi.lan
  user: pi
  password:
    from_secret: pi_password

steps:
  - name: build
    commands:
      - make
  - name: package
    commands:
      - make package
    when:
      event: tag
---
kind: pipeline
type: ssh
name: build-arch-linux

server:
  host: server.lan
  user:
    from_secret: server_user
  password:
    from_secret: server_password

steps:
  - name: build
    commands:
      - make
  - name: package & publish
    commands:
      - make package
      - curl -s "https://api.github.com/repos/lamarios/unifi-throughput-ncurses/releases/tags/${DRONE_TAG}" |  jq .id > release_id
      - cat release_id
      - curl --location --request POST "https://uploads.github.com/repos/lamarios/unifi-throughput-ncurses/releases/$(cat release_id)/assets?access_token=$(GITHUB_TOKEN)&name=$(ls unifi-throughput-*.tar.gz)" --header 'Accept: application/vnd.github.v3+json' --header 'Content-Type: image/svg+xml' --data-binary "@./$(ls unifi-throughput-*.tar.gz)"
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event: tag
